### PR TITLE
fix(helper-html): make the javascript protocol filter case insensitive

### LINKED ISSUE #683: Anchor tags with href protocol set to javascript isn't stripped out if capital letters are used
`<a href='javascript:console.log("hello");'>bad</a>` is stripped out but if you change the case
`<a href='JaVaScRiPt:console.log("hello");'>bad</a>` is not removed.

### PR DESCRIPTION
**Pull request by mwegman**
Fixes #683

### CODE REVIEW

File: packages/node_modules/@ciscospark/helper-html/test/unit/spec/html.js [hunk 1]
```diff
@@ -109,7 +109,7 @@ skipInNode(describe)(`html`, () => {
     },
     {
       it: `filters javascript: from a href`,
-      input: `<p><a href="javascript:window.close(); return false">click here</a></p>`,
```
Comment (adamweeks) [inline packages/node_modules/@ciscospark/helper-html/test/unit/spec/html.js]: Could we keep the original test case with an all lowercase test and make these mixed case tests a new test?

File: packages/node_modules/@ciscospark/helper-html/src/html.shim.js [hunk 2]
```diff
@@ -109,8 +109,8 @@ function _filterSync(processCallback, allowedTags, allowedStyles, html) {
           node.removeAttribute(attrName);
         }
         else if (attrName === `href` || attrName === `src`) {
-          const attrValue = node.attributes.getNamedItem(attrName).value.trim();
-          if (attrValue.indexOf(`javascript:`) === 0) {
+          const attrValue = node.attributes.getNamedItem(attrName).value.trim().toLocaleLowerCase();
```
Comment (ianwremmel) [inline packages/node_modules/@ciscospark/helper-html/src/html.shim.js]: please use `toLowerCase()` instead of `toLocaleLowerCase()`. We use `toLowerCase()` everywhere else. I'm open to consistently change to `toLocaleLowerCase()`, but IIRC, it actually has unexpected behaviors and doesn't help us in this case (since 'vbscript:' or 'javascript:' aren't localized).
