### PR TITLE
fix(tooling): change readme hack to prevent npm from pointing latest at a canary release

### LINKED ISSUE #12: npm install failing
`$ npm install ciscospark` seems to be failing for myself and a colleague, giving: 

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "install" "--save" "ciscospark"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5

npm ERR! No compatible version found: @ciscospark/spark-core@^0.7.0-alpha.f22f099e
npm ERR! Valid install targets:
npm ERR! 0.7.0-alpha.ce9393d4, 0.7.0-alpha.a5bc0482, 0.7.0-alpha.3266717c, 0.6.9, 0.6.6, 0.6.4, 0.6.3, 0.6.1, 0.6.0, 0.6.0-35, 0.6.0-34
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rilogan/Projects/SparkVideo/npm-debug.log
```

`$ npm view @ciscospark/plugin-phone versions` doesn't seem to show the asked for *0.7.0-alpha.f22f099e* version. 

For the record, `$ npm install ciscospark@0.6.9` works fine.

### PR DESCRIPTION
**Pull request by ianwremmel**
Fixes #12

### CODE REVIEW

File: tooling/jenkins-scripts/gate-jenkins.sh [hunk 1]
```diff
@@ -13,6 +13,15 @@ export XUNIT=true
 LOG_FILE="$(pwd)/test.log"
 rm -f "${LOG_FILE}"
 
+PWD=`pwd`
+
+cd /tmp
+ls lerna > /dev/null 2> /dev/null || git clone git@github.com:ianwremmel/lerna.git:
+git checkout de0f7f2
+npm link
+cd pwd
```
Comment (Josh-Dykstra) [inline tooling/jenkins-scripts/gate-jenkins.sh]: I think this is supposed to be the PWD you stored above.

**Comment by Josh-Dykstra** [comment]
LGTM
