### PR TITLE
Credentials 1: Add whileInFlight and some minor fixes

### LINKED ISSUE #143: Create a decorator that sets a boolean while a particular function is running
e.g. 

```javascript
class Token {
  @inFlight(`isRefreshing`)
  refresh(){}
}
```

### PR DESCRIPTION
**Pull request by ianwremmel**
Fixes #143

### CODE REVIEW

File: packages/spark-core/src/lib/storage/make-spark-store.js [hunk 1]
```diff
@@ -94,7 +94,7 @@ export default function makeSparkStore(type, spark) {
      * @param {string} namespace
      * @returns {Promise}
      */
-    @oneFlight((namespace) => namespace)
+    @oneFlight({keyFactorry: (namespace) => namespace})
```
Comment (Josh-Dykstra) [inline packages/spark-core/src/lib/storage/make-spark-store.js]: I think we have a typo here.

File: packages/common/src/while-in-flight.js [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+import {wrap} from 'lodash';
+import tap from './tap';
+
+/**
+ * While the promise returned by the decorated is unfullfilled, sets, the
+ * specified boolean on the target class to `true`
+ * @param {string} param
+ * @returns {Function}
+ */
+export default function whileInFlight(param) {
```
Comment (Josh-Dykstra) [inline packages/common/src/while-in-flight.js]: This is pretty interesting. Seems like a good starting point and I'm intrigued to see where else we end up using it.
